version: '3.8'
services:

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres

  app:
    build: .
    env_file:
     - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
